//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skytex.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Textos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Textos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Skytex.Recursos.Textos", typeof(Textos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap imgMision {
            get {
                object obj = ResourceManager.GetObject("imgMision", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap imgVsion {
            get {
                object obj = ResourceManager.GetObject("imgVsion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviso De Privacidad.
        /// </summary>
        public static string strAviso1 {
            get {
                return ResourceManager.GetString("strAviso1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacion Para Proveedores  \n Horarios de facturacion \n Horarios de acceso \n Etc..
        /// </summary>
        public static string strAviso2 {
            get {
                return ResourceManager.GetString("strAviso2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver Detalle.
        /// </summary>
        public static string strBoton1 {
            get {
                return ResourceManager.GetString("strBoton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postulate.
        /// </summary>
        public static string strBoton2 {
            get {
                return ResourceManager.GetString("strBoton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar Oferta.
        /// </summary>
        public static string strBoton3 {
            get {
                return ResourceManager.GetString("strBoton3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        public static string strBoton4 {
            get {
                return ResourceManager.GetString("strBoton4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string strBoton5 {
            get {
                return ResourceManager.GetString("strBoton5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regresa al Inicio.
        /// </summary>
        public static string strBoton6 {
            get {
                return ResourceManager.GetString("strBoton6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agrega Tu Comentario.
        /// </summary>
        public static string strBoton7 {
            get {
                return ResourceManager.GetString("strBoton7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        public static string strBoton8 {
            get {
                return ResourceManager.GetString("strBoton8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripcion de Vacante.
        /// </summary>
        public static string strLabel1 {
            get {
                return ResourceManager.GetString("strLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjunta tu Curriculum.
        /// </summary>
        public static string strLabel10 {
            get {
                return ResourceManager.GetString("strLabel10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si estás interesado envía tus datos por este medio y en breve nos comunicaremos contigo para agendar una entrevista..
        /// </summary>
        public static string strLabel11 {
            get {
                return ResourceManager.GetString("strLabel11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prestaciones.
        /// </summary>
        public static string strLabel2 {
            get {
                return ResourceManager.GetString("strLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de turno.
        /// </summary>
        public static string strLabel3 {
            get {
                return ResourceManager.GetString("strLabel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experiencia.
        /// </summary>
        public static string strLabel4 {
            get {
                return ResourceManager.GetString("strLabel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacantes.
        /// </summary>
        public static string strLabel5 {
            get {
                return ResourceManager.GetString("strLabel5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacto Skytex.
        /// </summary>
        public static string strLabel6 {
            get {
                return ResourceManager.GetString("strLabel6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu Email.
        /// </summary>
        public static string strLabel7 {
            get {
                return ResourceManager.GetString("strLabel7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu Nombre Completo.
        /// </summary>
        public static string strLabel8 {
            get {
                return ResourceManager.GetString("strLabel8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentarios.
        /// </summary>
        public static string strLabel9 {
            get {
                return ResourceManager.GetString("strLabel9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string strMenu1 {
            get {
                return ResourceManager.GetString("strMenu1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quienes Somos.
        /// </summary>
        public static string strMenu2 {
            get {
                return ResourceManager.GetString("strMenu2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolsa de Trabajo.
        /// </summary>
        public static string strMenu3 {
            get {
                return ResourceManager.GetString("strMenu3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        public static string strMenu4 {
            get {
                return ResourceManager.GetString("strMenu4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ir a Proveedores.
        /// </summary>
        public static string strMenu5 {
            get {
                return ResourceManager.GetString("strMenu5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empleados/Operadores.
        /// </summary>
        public static string strMenu6 {
            get {
                return ResourceManager.GetString("strMenu6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skytex.
        /// </summary>
        public static string strNombreSky1 {
            get {
                return ResourceManager.GetString("strNombreSky1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SkyTrade.
        /// </summary>
        public static string strNombreSky2 {
            get {
                return ResourceManager.GetString("strNombreSky2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SkyRug.
        /// </summary>
        public static string strNombreSky3 {
            get {
                return ResourceManager.GetString("strNombreSky3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SkyMatt.
        /// </summary>
        public static string strNombreSky4 {
            get {
                return ResourceManager.GetString("strNombreSky4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SkyFelt.
        /// </summary>
        public static string strNombreSky5 {
            get {
                return ResourceManager.GetString("strNombreSky5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiber Home.
        /// </summary>
        public static string strNombreSky6 {
            get {
                return ResourceManager.GetString("strNombreSky6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body Fx.
        /// </summary>
        public static string strNombreSky7 {
            get {
                return ResourceManager.GetString("strNombreSky7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SkyDeco.
        /// </summary>
        public static string strNombreSky8 {
            get {
                return ResourceManager.GetString("strNombreSky8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En Skytex estamos orgullosos de ser uno de los fabricantes más importantes en la región del Tratado de Libre Comercio de América del Norte y Latinoamérica de telas de poliéster de alta torsión, así como de las telas sintéticas con spandex del tejido circular, teñidas y estampadas..
        /// </summary>
        public static string strParrafo1 {
            get {
                return ResourceManager.GetString("strParrafo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nos encontramos ubicados en Corredor Industrial Quetzalcóatl, Huejotzingo, Pue..
        /// </summary>
        public static string strParrafo10 {
            get {
                return ResourceManager.GetString("strParrafo10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo Skytex está integrado por Skytex, empresa dedicada a la fabricación de tejidos planos y de punto producidos con fibras sintéticas y artificiales de alta calidad. Skyfelt especializada en la fabricación de fieltros no tejidos. Skymatt fabricante de fibras regeneradas y productos no tejidos para la industria colchonera, mueblería y automotriz. Sus instalaciones se localizan en el Parque Industrial Huejotzingo, en el corazón del estado de Puebla y abarcan más de 80,000 metros cuadrados.
        /// </summary>
        public static string strParrafo11 {
            get {
                return ResourceManager.GetString("strParrafo11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En Skytex estamos convencidos del papel fundamental que la tecnología de vanguardia cumple para atender adecuadamente la demanda de los mercados en una economía global. Por eso, nos hemos propuesto contar con la tecnología y el equipamiento más moderno disponible en el mundo, como son los sistemas digitales aplicados al diseño, grabado, tejido y estampado de las telas, así como los más avanzados sistemas de control de la producción que permiten supervisar cada uno de los pasos de la totalidad de los proceso [rest of string was truncated]&quot;;.
        /// </summary>
        public static string strParrafo12 {
            get {
                return ResourceManager.GetString("strParrafo12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoy en día, el uso intensivo y adecuado de la tecnología nos ha permitido contar con procesos altamente controlados mediante sistemas totalmente computarizados, gracias a lo cual podemos garantizar de manera permanente la calidad superior de nuestras telas..
        /// </summary>
        public static string strParrafo13 {
            get {
                return ResourceManager.GetString("strParrafo13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ofrecer siempre calidad superior en todos nuestros productos es la meta y el compromiso establecido con nuestros clientes. Para dar cumplimiento a lo anterior, contamos con un sistema especializado de código de barras que monitorea y evalúa todos los procesos con la finalidad de asegurar el cumplimiento de los estándares de calidad más altos a nivel internacional..
        /// </summary>
        public static string strParrafo14 {
            get {
                return ResourceManager.GetString("strParrafo14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cada uno de nuestros insumos y materias primas, hilos, colorantes y químicos, etc., así como los productos finales son sujetos a una inspección rigurosa utilizando los equipos tecnológicamente más avanzados, controlando con ellos el cumplimiento de especificaciones que nos permiten garantizar la completa satisfacción de nuestros clientes..
        /// </summary>
        public static string strParrafo15 {
            get {
                return ResourceManager.GetString("strParrafo15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionalmente a nuestros rigurosos controles de producción contamos con un sistema de monitoreo que nos permite dar seguimiento a los pedidos de nuestros clientes a fin de asegurar la entrega oportuna de nuestros productos..
        /// </summary>
        public static string strParrafo16 {
            get {
                return ResourceManager.GetString("strParrafo16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La ubicación geográfica de las instalaciones de Skytex complementa las facilidades para la prestación de un servicio de excelencia. Nuestra localización en la zona centro de México se traduce en distancias más cortas y facilidad de comunicación con nuestros clientes y proveedores para de esta forma hacer más eficiente el flujo de los insumos y materias primas requeridas en nuestros procesos de producción, así como de nuestros productos terminados. Asimismo, por ser de origen TLC, nuestros productos gozan de [rest of string was truncated]&quot;;.
        /// </summary>
        public static string strParrafo17 {
            get {
                return ResourceManager.GetString("strParrafo17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somos una empresa que cumple con un rol activo en favor de la tecnología. No solo cumplimos con las regulaciones gubernamentales en el ámbito de la industria, sino que también vamos más allá de las especificaciones locales para cumplir con nuestros propios objetivos y programas en materia ecológica..
        /// </summary>
        public static string strParrafo18 {
            get {
                return ResourceManager.GetString("strParrafo18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contamos con una planta para el tratamiento biológico de aguas, su reciclamiento y reutilización en nuestros procesos de producción. Disponemos de un sistema de recolección de aguas pluviales que nos permite almacenar, tratar y reutilizar 12,000 m2 de agua. Recuperamos el vapor condensado para ahorrar energía en nuestros procesos, y por supuesto, cumplimos con todas las regulaciones sobre emisiones de gases y tratamiento de desperdicios..
        /// </summary>
        public static string strParrafo19 {
            get {
                return ResourceManager.GetString("strParrafo19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debido a su equipamiento y tecnología de punta, nuestra planta bien puede ser considerada como una de las más modernas de su tipo a nivel mundial..
        /// </summary>
        public static string strParrafo2 {
            get {
                return ResourceManager.GetString("strParrafo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El desarrollo de una empresa modera de clase internacional con tecnología de punta que participe como líder en la satisfacción de las necesidades del mercado nacional e internacional a través de producir y comercializar toda una gama de productos textiles con alto grado de profesionalismo.
        /// </summary>
        public static string strParrafo20 {
            get {
                return ResourceManager.GetString("strParrafo20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Visión de Grupo Skytex es ser reconocido por sus clientes como el proveedor más confiable, mejorando continuamente la calidad de sus productos y servicios; por sus proveedores como el cliente que promueve, junto con ellos el desarrollo y la mejora de sistemas y procesos de calidad total; por la comunidad como la empresa que permanentemente genera oportunidades de empleo y desarrollo y que es cuidadosa del medio ambiente; y por su personal como la empresa que promueve el bienestar, la seguridad, la calida [rest of string was truncated]&quot;;.
        /// </summary>
        public static string strParrafo21 {
            get {
                return ResourceManager.GetString("strParrafo21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skyman es nuestro colaborador y ejemplo a seguir, porque todos los días vive los valores de Skytex mientras realiza su trabajo..
        /// </summary>
        public static string strParrafo22 {
            get {
                return ResourceManager.GetString("strParrafo22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos y cada uno de nosotros debemos seguir el ejemplo de Skyman, para convertirnos en colaboradores excelentes. Todos Nuestros Valores, están expresados en el CIRCULO DEL EXITO, que representa el avance ascendente hacia los objetivos organizacionales, a través de su cumplimiento..
        /// </summary>
        public static string strParrafo23 {
            get {
                return ResourceManager.GetString("strParrafo23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los que trabajamos en Skytex somos gente  comprometida  con nuestros clientes quienes merecen la más alta calidad, nos esforzamos en mantener con ellos una comunicación clara y precisa para lograr entender sus necesidades y proporcionarles un producto innovador que cumpla o supere sus expectativas de calidad y entrega a tiempo..
        /// </summary>
        public static string strParrafo24 {
            get {
                return ResourceManager.GetString("strParrafo24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicamos la tecnología más avanzada de nuestro género en el proceso de fabricación, con efectividad y eficiencia. Atendemos las necesidades propias de la empresa desarrollando continuamente al personal contemplando aspectos técnicos y de seguridad, asimismo protegemos el entorno ecológico para el bienestar de la sociedad..
        /// </summary>
        public static string strParrafo25 {
            get {
                return ResourceManager.GetString("strParrafo25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La obtención de mejores resultados financieros como productos de una operación eficiente en todas sus áreas, la retribución justa y equitativa del equipo de trabajo y del desarrollo de los recursos humanos que lo conforman, así como el mantenimiento de una posición competitiva en el mercado..
        /// </summary>
        public static string strParrafo26 {
            get {
                return ResourceManager.GetString("strParrafo26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aportamos lo mejor de cada uno, promoviendo la comunicación, colaboración e integración, desarrollando un liderazgo efectivo para alcanzar los objetivos del grupo..
        /// </summary>
        public static string strParrafo27 {
            get {
                return ResourceManager.GetString("strParrafo27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contribuimos al cuidado del medio ambiente laboral y social, siendo responsables y cuidadosos de nuestra integridad física y de los demás..
        /// </summary>
        public static string strParrafo28 {
            get {
                return ResourceManager.GetString("strParrafo28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desarrollamos a nuestro personal para mantenerlo actualizado de acuerdo a los requerimientos de nuestro mercado..
        /// </summary>
        public static string strParrafo29 {
            get {
                return ResourceManager.GetString("strParrafo29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gracias a la integración vertical de todos los procesos, desde el torcido de hilo hasta el estampado de la tela, estamos en condiciones de garantizar la más alta calidad en todos nuestros productos, y así, ofrecer el mejor de los servicios a nuestros clientes..
        /// </summary>
        public static string strParrafo3 {
            get {
                return ResourceManager.GetString("strParrafo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ejecutamos con sentido de urgencia nuestro trabajo para lograr la calidad y eficiencia desde la primera vez..
        /// </summary>
        public static string strParrafo30 {
            get {
                return ResourceManager.GetString("strParrafo30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superamos las expectativas del cliente..
        /// </summary>
        public static string strParrafo31 {
            get {
                return ResourceManager.GetString("strParrafo31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puedes verificar los siguientes datos en tu credencial.
        /// </summary>
        public static string strParrafo32 {
            get {
                return ResourceManager.GetString("strParrafo32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Empleado:.
        /// </summary>
        public static string strParrafo33 {
            get {
                return ResourceManager.GetString("strParrafo33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gracias por tu comentario.
        /// </summary>
        public static string strParrafo34 {
            get {
                return ResourceManager.GetString("strParrafo34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresa tu comentario en el siguiente espacio.
        /// </summary>
        public static string strParrafo35 {
            get {
                return ResourceManager.GetString("strParrafo35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos no son correctos intente de nuevo.
        /// </summary>
        public static string strParrafo36 {
            get {
                return ResourceManager.GetString("strParrafo36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su comentario ha sido enviado correctamente.
        /// </summary>
        public static string strParrafo37 {
            get {
                return ResourceManager.GetString("strParrafo37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFC:.
        /// </summary>
        public static string strParrafo38 {
            get {
                return ResourceManager.GetString("strParrafo38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo Skytex consta de un grupo de empresas que gracias a su tecnología de punta y determinación permiten garantizar la más alta calidad en todos nuestros productos. Grupo Skytex se enfoca en la industria de la confección, moda, decoración del hogar, limpieza, industria colchonera, mueblera y otras. Nuestra planta está ubicada en el Parque Industrial en Huejotzingo, Puebla y abarca más de 80,000 metros cuadrados. Grupo Skytex cumple con todas los normas nacionales al igual que internacionales..
        /// </summary>
        public static string strParrafo4 {
            get {
                return ResourceManager.GetString("strParrafo4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El principal mercado al que nuestros productos están destinados es el de la moda y confección, por lo que la variedad de las telas en cuanto a texturas, acabados, colores y estampados, adquiere importancia relevante ya que permanentemente tenemos que ofrecer alternativas de vanguardia, de acuerdo a las tendencias de marca la moda internacional..
        /// </summary>
        public static string strParrafo5 {
            get {
                return ResourceManager.GetString("strParrafo5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;La calidad es primero&quot;.
        /// </summary>
        public static string strParrafo6 {
            get {
                return ResourceManager.GetString("strParrafo6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tejido Plano y Circular.  Surge en el país como la primera fábrica para telas de alta torsión. Utilizando fibras de poliéster para ofrecer al mercado un producto nacional capaz de sustituir y mejorar los productos que se tenían que importar..
        /// </summary>
        public static string strParrafo7 {
            get {
                return ResourceManager.GetString("strParrafo7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listones. A finales del año 2006 iniciamos la fabricación de listones con tecnología avanzada y un alto control de calidad; elaborados con nylon y poliéster, ofreciendo alta resistencia y gran variedad en cuanto a tamaño y colorido..
        /// </summary>
        public static string strParrafo8 {
            get {
                return ResourceManager.GetString("strParrafo8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medio Ambiente. Como empresa no solo cumplimos con regulaciones gubernamentales en el ámbito de la industria, sino que también cumplimos con nuestros propios objetivos en materia ecológica..
        /// </summary>
        public static string strParrafo9 {
            get {
                return ResourceManager.GetString("strParrafo9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skytex México SA de CV, Skymatt SA de CV, Skyfelt SA de CV, Skyrug SA de CV y Global Financial Solution GFSK SA de CV de CV SOFOM ENR ( conjuntamente denominadas GRUPO SKYTEX ) son los responsables del tratamiento ( uso ) de sus datos personales..
        /// </summary>
        public static string strParrafoPrivacidad1 {
            get {
                return ResourceManager.GetString("strParrafoPrivacidad1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usted o su representante legal podrán en cualquier momento solicitar a Grupo Skytex Acceder, Rectificar, Cancelar u Oponerse ( ARCO ), limitar su uso o revocar el uso de sus Datos Personales ( derechos ARCO ) y conocer los procedimientos para ejercer dichos derechos, mediante comunicación al siguiente correo electrónico : atención.avisoprivacidad@skytex.com.mx.
        /// </summary>
        public static string strParrafoPrivacidad10 {
            get {
                return ResourceManager.GetString("strParrafoPrivacidad10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En caso de que usted sea proveedor persona física de Grupo Skytex, apoderado y/o accionista de algún proveedor, y sea persona física, le aplicará este Aviso de Privacidad, sujetándose la información a los fines que se estipulen en los documentos correspondientes..
        /// </summary>
        public static string strParrafoPrivacidad11 {
            get {
                return ResourceManager.GetString("strParrafoPrivacidad11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este Aviso de Privacidad se rige por la LEY y las demás leyes y reglamentos de los Estados Unidos Mexicanos. La aceptación de este Aviso de Privacidad implica una aceptación por escrito de los términos del mismo y su sometimiento expreso a los tribunales de la Ciudad de México, Distrito Federal, para cualquier controversia o reclamación derivada de este Aviso de Privacidad..
        /// </summary>
        public static string strParrafoPrivacidad12 {
            get {
                return ResourceManager.GetString("strParrafoPrivacidad12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corredor Industrial Quetzalcóatl, Huejotzingo, Pue. Responsable del tratamiento de sus datos personales El responsable del tratamiento de sus datos personales será aquella entidad comercial de las mencionadas en el primer párrafo de éste aviso..
        /// </summary>
        public static string strParrafoPrivacidad2 {
            get {
                return ResourceManager.GetString("strParrafoPrivacidad2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para efectos de la LEY se entiende por DATOS PERSONALES cualquier información concerniente al TITULAR que firma el presente Aviso, y/o DATOS PERSONALES SENSIBLES, y/o aquellos datos personales que afecten a la esfera más íntima de su titular, o cuya utilización indebida pueda dar origen a discriminación o conlleve un riesgo grave para éste. En particular, se consideran sensibles aquellos que puedan revelar aspectos como origen racial o étnico, estado de salud presente y futuro, información genética, creenci [rest of string was truncated]&quot;;.
        /// </summary>
        public static string strParrafoPrivacidad3 {
            get {
                return ResourceManager.GetString("strParrafoPrivacidad3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo Skytex recabará los datos personales necesarios que sus departamentos de recursos humanos, compras y crédito y cobranza requieran para la integración de expedientes individuales personalizados, tendientes a atender y formalizar las peticiones inherentes a esos departamentos..
        /// </summary>
        public static string strParrafoPrivacidad4 {
            get {
                return ResourceManager.GetString("strParrafoPrivacidad4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo Skytex podrá recabar sus datos personales de distintas formas: cuando usted los proporciones directamente, cuando visite nuestro sitio de internet, lo envié por correo electrónico o servicios en línea y cuando obtenemos información a través de otras fuentes que Grupo Skytex podrá recabar los siguientes datos de manera enunciativa mas no limitativa : Nombre, domicilio, fecha de nacimiento, lugar de nacimiento, ocupación, actividad o giro comercial, número telefónico y celular, correo electrónico, Clave [rest of string was truncated]&quot;;.
        /// </summary>
        public static string strParrafoPrivacidad5 {
            get {
                return ResourceManager.GetString("strParrafoPrivacidad5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo Skytex podrá transferir sus datos personales a terceros mexicanos o extranjeros que le provean de servicio necesarios para su operación, así como sus asociadas, afiliadas y partes relacionadas. En dichos supuestos, Grupo Skytex recomendará todas las medidas necesarias para que los terceros mencionados que tengan acceso a sus datos personales cumplan con la política de privacidad de Grupo Skytex así como con los principios de protección de datos personales establecidos en la Ley..
        /// </summary>
        public static string strParrafoPrivacidad6 {
            get {
                return ResourceManager.GetString("strParrafoPrivacidad6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La temporalidad del manejo y tratamiento de los Datos Personales, dependerá directamente de la relación jurídica que se tenga celebrada con Grupo Skytex, así como de las obligaciones exigidas por la legislación vigente y las autoridades competentes. En todos los casos la información será conservada por el plazo necesario para el cumplimiento de las finalidades que justificaron su tratamiento. Así como para dar cumplimiento a las responsabilidades nacidas como consecuencia del propio tratamiento..
        /// </summary>
        public static string strParrafoPrivacidad7 {
            get {
                return ResourceManager.GetString("strParrafoPrivacidad7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo Skytex cumple los principios rectores de protección de Datos Personales de Licitud, Consentimiento, Información, Finalidad, Proporcionalidad, Lealtad, Calidad y Responsabilidad, establecidos por la LEY, así mismo adopta las medidas necesarias para su aplicación., adoptará los medios y mecanismos necesarios y suficientes para procurar que el tratamiento de los Datos Personales en apego a la legislación aplicable; privilegiando en todo momento la protección de sus intereses y privacidad, mediante su deb [rest of string was truncated]&quot;;.
        /// </summary>
        public static string strParrafoPrivacidad8 {
            get {
                return ResourceManager.GetString("strParrafoPrivacidad8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo Skytex se reserva el derecho de efectuar en cualquier momento modificaciones ó actualizaciones al presente Aviso de Privacidad, atendiendo en su caso, a cambios legislativos, políticas internas o bien a nuevos requerimientos para la prestación u ofrecimiento de nuestros productos. Estas modificaciones estarán disponibles al público en nuestra dirección web www.skytex.com.mx.
        /// </summary>
        public static string strParrafoPrivacidad9 {
            get {
                return ResourceManager.GetString("strParrafoPrivacidad9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SkyFelt es una empresa dedicada a la fabricación de fieltros no tejidos, utilizando básicamente en el mercado de las manualidades para diseñar y elaborar productos de ornato; al igual que todas las empresas del Grupo Skytex, nuestro compromiso es ofrecer un producto de clase mundial. Para lograr tales objetivos, contamos con tecnología de punta y con base en el sistema profiling hemos podido lograr una regularidad excepcional en el acabado y ancho de nuestros productos..
        /// </summary>
        public static string strParrafoSkyFelt1 {
            get {
                return ResourceManager.GetString("strParrafoSkyFelt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asimismo, la forma como están diseñados nuestros procesos nos permite tener la flexibilidad necesaria para poder satisfacer los requerimientos y necesidades específicas de nuestros clientes y de esta forma proponer soluciones concretas a diferentes tipos de problemas dentro de los mercados que atendemos..
        /// </summary>
        public static string strParrafoSkyFelt2 {
            get {
                return ResourceManager.GetString("strParrafoSkyFelt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para asegurar la consistencia en la calidad de los productos, hemos implementado sistemas avanzados de control y monitoreo computarizado, los cuales nos permiten tener un alto grado de eficiencia en el desarrollo de los procesos, así como en la calidad del producto terminado..
        /// </summary>
        public static string strParrafoSkyFelt3 {
            get {
                return ResourceManager.GetString("strParrafoSkyFelt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Como empresa, nuestro compromiso de mejora continua, se extiende a la atención y servicio a nuestros clientes, reflejándose en una promesa de venta que se traduce en poder ofrecer el mejor producto de su clase en el mercado, a un precio justo, entregado en el lugar y tiempo convenidos..
        /// </summary>
        public static string strParrafoSkyFelt4 {
            get {
                return ResourceManager.GetString("strParrafoSkyFelt4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POLÍTICA DE CALIDAD.
        /// </summary>
        public static string strParrafoSkyMatt1 {
            get {
                return ResourceManager.GetString("strParrafoSkyMatt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Los que trabajamos en Skymatt somos gente comprometida con nuestros clientes quienes merecen la más alta prioridad, nos esforzamos en mantener con ellos una comunicación clara y precisa para lograr entender sus necesidades y proporcionales un producto innovador, para acojinamiento de la industria del colchón y aislante acústico para la industria automotriz, que cumpla o supere las expectativas de calidad y entrega a tiempo..
        /// </summary>
        public static string strParrafoSkyMatt2 {
            get {
                return ResourceManager.GetString("strParrafoSkyMatt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicamos tecnología avanzada en el proceso de fabricación, con efectividad y eficiencia. Mejoramos continuamente contemplando aspectos técnicos, de calidad y de seguridad, asimismo protegemos el entorno ecológico para bienestar de la sociedad cumpliendo requerimientos legales y voluntarios&quot;.
        /// </summary>
        public static string strParrafoSkyMatt3 {
            get {
                return ResourceManager.GetString("strParrafoSkyMatt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerente General.
        /// </summary>
        public static string strParrafoSkyMatt4 {
            get {
                return ResourceManager.GetString("strParrafoSkyMatt4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acerca de Skytex México..
        /// </summary>
        public static string strSubTitulo1 {
            get {
                return ResourceManager.GetString("strSubTitulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trabajo en Equipo.
        /// </summary>
        public static string strSubTitulo10 {
            get {
                return ResourceManager.GetString("strSubTitulo10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seguridad y Medio Ambiente.
        /// </summary>
        public static string strSubTitulo11 {
            get {
                return ResourceManager.GetString("strSubTitulo11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacitación.
        /// </summary>
        public static string strSubTitulo12 {
            get {
                return ResourceManager.GetString("strSubTitulo12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calidad y Productividad.
        /// </summary>
        public static string strSubTitulo13 {
            get {
                return ResourceManager.GetString("strSubTitulo13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicio al Cliente.
        /// </summary>
        public static string strSubTitulo14 {
            get {
                return ResourceManager.GetString("strSubTitulo14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conócenos.
        /// </summary>
        public static string strSubTitulo2 {
            get {
                return ResourceManager.GetString("strSubTitulo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuestra Misión.
        /// </summary>
        public static string strSubTitulo3 {
            get {
                return ResourceManager.GetString("strSubTitulo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuestra Visión.
        /// </summary>
        public static string strSubTitulo4 {
            get {
                return ResourceManager.GetString("strSubTitulo4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuestros Valores.
        /// </summary>
        public static string strSubTitulo5 {
            get {
                return ResourceManager.GetString("strSubTitulo5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Círculo del Éxito.
        /// </summary>
        public static string strSubTitulo6 {
            get {
                return ResourceManager.GetString("strSubTitulo6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Política de Calidad.
        /// </summary>
        public static string strSubTitulo7 {
            get {
                return ResourceManager.GetString("strSubTitulo7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valores Grupales.
        /// </summary>
        public static string strSubTitulo8 {
            get {
                return ResourceManager.GetString("strSubTitulo8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valores Organizacionales.
        /// </summary>
        public static string strSubTitulo9 {
            get {
                return ResourceManager.GetString("strSubTitulo9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En Skytex.
        /// </summary>
        public static string strTitulo1 {
            get {
                return ResourceManager.GetString("strTitulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ofertas Disponibles en Skytex.
        /// </summary>
        public static string strTitulo10 {
            get {
                return ResourceManager.GetString("strTitulo10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oferta.
        /// </summary>
        public static string strTitulo11 {
            get {
                return ResourceManager.GetString("strTitulo11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opciones.
        /// </summary>
        public static string strTitulo12 {
            get {
                return ResourceManager.GetString("strTitulo12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Página en Construcción.
        /// </summary>
        public static string strTitulo13 {
            get {
                return ResourceManager.GetString("strTitulo13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En breve la página estará disponible.
        /// </summary>
        public static string strTitulo14 {
            get {
                return ResourceManager.GetString("strTitulo14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviso de Privacidad Skytex..
        /// </summary>
        public static string strTitulo15 {
            get {
                return ResourceManager.GetString("strTitulo15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TERMINOS DE LA LEY FEDERAL DE PROTECCIÓN DE DATOS PERSONALES EN POSESIÓN DE LOS PARTICULARES Y SU REGLAMENTO (EN LO SUCESIVO LA “LEY”).
        /// </summary>
        public static string strTitulo16 {
            get {
                return ResourceManager.GetString("strTitulo16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identidad y domicilio del responsable:.
        /// </summary>
        public static string strTitulo17 {
            get {
                return ResourceManager.GetString("strTitulo17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domicilio de Grupo Skytex:.
        /// </summary>
        public static string strTitulo18 {
            get {
                return ResourceManager.GetString("strTitulo18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se entiende por Datos Personales:.
        /// </summary>
        public static string strTitulo19 {
            get {
                return ResourceManager.GetString("strTitulo19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultimas Noticias.
        /// </summary>
        public static string strTitulo2 {
            get {
                return ResourceManager.GetString("strTitulo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalidad de tratamiento de sus Datos:.
        /// </summary>
        public static string strTitulo20 {
            get {
                return ResourceManager.GetString("strTitulo20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos personales que recaba Grupo Skytex:.
        /// </summary>
        public static string strTitulo21 {
            get {
                return ResourceManager.GetString("strTitulo21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferencia de datos personales:.
        /// </summary>
        public static string strTitulo22 {
            get {
                return ResourceManager.GetString("strTitulo22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plazos del tratamiento de sus Datos Personales:.
        /// </summary>
        public static string strTitulo23 {
            get {
                return ResourceManager.GetString("strTitulo23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protección de Datos:.
        /// </summary>
        public static string strTitulo24 {
            get {
                return ResourceManager.GetString("strTitulo24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificaciones al Aviso de Privacidad:.
        /// </summary>
        public static string strTitulo25 {
            get {
                return ResourceManager.GetString("strTitulo25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derechos ARCO y/o revocación de consentimiento para el uso y tratamiento de datos personales:.
        /// </summary>
        public static string strTitulo26 {
            get {
                return ResourceManager.GetString("strTitulo26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proveedores de Grupo Skytex Personas Físicas:.
        /// </summary>
        public static string strTitulo27 {
            get {
                return ResourceManager.GetString("strTitulo27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legislación y jurisdicción aplicables:.
        /// </summary>
        public static string strTitulo28 {
            get {
                return ResourceManager.GetString("strTitulo28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presidente de Skytex México S.A de C.V.
        /// </summary>
        public static string strTitulo29 {
            get {
                return ResourceManager.GetString("strTitulo29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo Skytex.
        /// </summary>
        public static string strTitulo3 {
            get {
                return ResourceManager.GetString("strTitulo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quejas y Sugerencias.
        /// </summary>
        public static string strTitulo30 {
            get {
                return ResourceManager.GetString("strTitulo30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dentro de Skytex.
        /// </summary>
        public static string strTitulo4 {
            get {
                return ResourceManager.GetString("strTitulo4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encuéntranos En.
        /// </summary>
        public static string strTitulo5 {
            get {
                return ResourceManager.GetString("strTitulo5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacto Vacantes.
        /// </summary>
        public static string strTitulo6 {
            get {
                return ResourceManager.GetString("strTitulo6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misión.
        /// </summary>
        public static string strTitulo7 {
            get {
                return ResourceManager.GetString("strTitulo7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visión.
        /// </summary>
        public static string strTitulo8 {
            get {
                return ResourceManager.GetString("strTitulo8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valores.
        /// </summary>
        public static string strTitulo9 {
            get {
                return ResourceManager.GetString("strTitulo9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skytex te agradece la visita..
        /// </summary>
        public static string strVisita {
            get {
                return ResourceManager.GetString("strVisita", resourceCulture);
            }
        }
    }
}
