//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class cccatcc
    {
        public string cc_tipo { get; set; }
        public string cc_cve { get; set; }
        public string nom1 { get; set; }
        public string nom2 { get; set; }
        public string rfc { get; set; }
        public string dir1 { get; set; }
        public string dir2 { get; set; }
        public string cd_cve { get; set; }
        public string pais_cve { get; set; }
        public string cp { get; set; }
        public string telef1 { get; set; }
        public string telef2 { get; set; }
        public string telef3 { get; set; }
        public string fax1 { get; set; }
        public string fax2 { get; set; }
        public string fax3 { get; set; }
        public string atencion1 { get; set; }
        public string atencion2 { get; set; }
        public string atencion3 { get; set; }
        public string puesto1 { get; set; }
        public string puesto2 { get; set; }
        public string puesto3 { get; set; }
        public string cta_num { get; set; }
        public short plazo_nrm { get; set; }
        public decimal pct_desc { get; set; }
        public short plazo_pp { get; set; }
        public decimal pct_descpp { get; set; }
        public System.DateTime fec_ultact { get; set; }
        public string id_ultact { get; set; }
        public bool sw_fijo { get; set; }
        public bool sw_retencion { get; set; }
        public System.DateTime fec_limrev { get; set; }
        public decimal lim_cre { get; set; }
        public string tm_lim_cre { get; set; }
        public string obs { get; set; }
        public short status { get; set; }
        public string forpag_cve { get; set; }
        public bool sw_docto { get; set; }
        public bool sw_plazomes { get; set; }
        public string rev_frec { get; set; }
        public string rev_tipo { get; set; }
        public string rev_dias { get; set; }
        public System.DateTime rev_horaini { get; set; }
        public System.DateTime rev_horafin { get; set; }
        public string doc_frec { get; set; }
        public string doc_tipo { get; set; }
        public string doc_dias { get; set; }
        public System.DateTime doc_horaini { get; set; }
        public System.DateTime doc_horafin { get; set; }
        public string pago_frec { get; set; }
        public string pago_tipo { get; set; }
        public string pago_dias { get; set; }
        public System.DateTime pago_horaini { get; set; }
        public System.DateTime pago_horafin { get; set; }
        public string if_cve { get; set; }
        public string rfc_fin { get; set; }
    }
}
